[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# .streamlit/config.toml
[server]
headless = true
port = 8501
enableCORS = false

[server]
folderWatchBlacklist = [".venv", "data", "logs"]

